// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_ArcCO2;
lv_obj_t * ui_LabelCo2Count;
lv_obj_t * ui_LabelCo2;
lv_obj_t * ui_LabelCo2Ppm;
lv_obj_t * ui_LabelSdFree;
lv_obj_t * ui_LabelLfsUsed;
lv_obj_t * ui_ImageAPMode;
lv_obj_t * ui_LabelApUsers;
lv_obj_t * ui_ImageLocalWiFI;
lv_obj_t * ui_LabelipAdress;
lv_obj_t * ui_ImageNoWiFi;
lv_obj_t * ui_BarHumidity;
lv_obj_t * ui_BarTemperature;
lv_obj_t * ui_BarPressure;
lv_obj_t * ui_ImageTemperature;
lv_obj_t * ui_ImageHumidity;
lv_obj_t * ui_ImagePressure;
lv_obj_t * ui_LabelTemperature;
lv_obj_t * ui_LabelHumidity;
lv_obj_t * ui_LabelPressure;
lv_obj_t * ui_LabelAirQualityIndx;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
